### ISSUE TITLE
Is there anything that needs to be done to save session to store immediately?

### ISSUE THREAD

**Issue by gajus** [mgcrea/fastify-session#17]
If I do `request.session.set('userAccountId', newUserAccountId)`, is there anything else I need to do to ensure that this session is _immediately_ updated in Redis?

I am debugging the root cause of why there is a (short) delay between when we set `request.session.set('userAccountId', newUserAccountId)` and when this value is available to all instances running our HTTP service.

**Comment by mgcrea** [comment]
The session is saved back to the store just before the reply so that it can save all changes at once, see https://github.com/mgcrea/fastify-session/blob/master/src/plugin.ts#L120

You should be able to save it ASAP using `await session.save();` to have it immediately updated (you will just end up with two saves).

**Comment by gajus** [comment]
That's good to know! Thank you
